apiVersion: v1
kind: Service
metadata:
  name: nginx-la
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    environment: dev
    purpose: practise
  ports:
  - protocol: TCP
    port: 80 # servie port
    targetPort: 80 #Target port
    